# This is a basic workflow to help you get started with Actions
name: Metrics

# Controls when the workflow will run
on:
  # Schedule daily updates
  schedule: 
    - cron: "0 0 * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "github-metrics"
  # github-metrics:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
    
  #   environment: 
  #     name: production
      
  #   permissions:
  #     contents: write
      
  #   steps:
  #     - uses: lowlighter/metrics@latest
  #       with:
  #         token: ${{ secrets.ACCESS_TOKEN_CLASSIC }}

  achievements-metrics:
      runs-on: ubuntu-latest
      
      environment:
          name: production

      permissions: 
          contents: write

      steps:
        - name: Achievements Metrics
          uses: lowlighter/metrics@latest
          with:
            optimize: svg, css, xml
            use_prebuilt_image: yes
            config_output: svg
            config_timezone: Asia/Bangkok

            base_indepth: yes
            repositories_affiliations: owner, collaborator, organization_member
            repositories_forks: yes
            
            filename: achievements.svg
            token: ${{ secrets.ACCESS_TOKEN_CLASSIC }}
            base: ""
            plugin_achievements: yes
            plugin_achievements_only: >-
              polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
              scripter, packager, explorer, infographile, manager
            plugin_achievements_display: compact
            plugin_achievements_threshold: X

  isocalender-metrics:
    runs-on: ubuntu-latest
    
    environment: 
      name: production
      
    permissions:
      contents: write
      
    steps:
      - name: Calender Metrics
        uses: lowlighter/metrics@latest
        with:
          optimize: svg, css, xml
          use_prebuilt_image: yes
          config_output: svg
          config_timezone: Asia/Bangkok

          base_indepth: yes
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: yes
        
          filename: isocalender.svg
          token: ${{ secrets.ACCESS_TOKEN_CLASSIC }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
